In [1]:
using Pkg

Pkg.activate(".")

  Activating project at `~/Documents/Uni/Master/MA/visual_analysis`


In [2]:
using JLD2
using GLMakie
using Dates

In [69]:
# include("utils.jl")
include("visual_utils.jl")

temporal_pattern_integration (generic function with 1 method)

In [4]:
# data_base_path = "/home/denis/workspace/data/ma_data"
data_base_path = "/mnt/bigdrive/Datasets/master_thesis_data"

"/mnt/bigdrive/Datasets/master_thesis_data"

In [13]:
ps_data_monthly_path = joinpath(data_base_path, "ps_data_monthly")
psl_data_monthly_path = joinpath(data_base_path, "psl_data_monthly")
pr_data_monthly_path = joinpath(data_base_path, "preciptation_data_monthly")
ivt_data_monthly_path = joinpath(data_base_path, "ivt_fields_monthly")
eof_data_path = joinpath(data_base_path, "eof_data_v3.2")

"/mnt/bigdrive/Datasets/master_thesis_data/eof_data_v3.2"

In [6]:
function filter_winter_season(time_element)
    winter_months = [12, 1, 2, 3]
    for wm in winter_months
        if month(time_element) == wm
            return true
        end
    end
    return false
end

filter_winter_season (generic function with 1 method)

In [7]:
function winter_timelimit(timeelement)
    return filter_winter_season(timeelement) && timeelement < DateTime(2100, 12, 31)
end

winter_timelimit (generic function with 1 method)

In [10]:
(ivt_historical_monthly, ivt_ssp126_monthly, ivt_ssp585_monthly) = build_ensemble_data(ivt_data_monthly_path, "historical", "ssp126", "ssp585"; file_range_selection=:, data_field_id="ivt", member_range=1:50, filterfun = winter_timelimit)

Handling scenario historical ...
Handling scenario ssp126 ...
Handling scenario ssp585 ...


3-element Vector{EnsembleSimulation}:
 EnsembleSimulation("historical", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-14T21:00:00"), DateTime("1850-03-16T09:00:00"), DateTime("1850-12-16T09:00:00"), DateTime("1851-01-16T09:00:00"), DateTime("1851-02-14T21:00:00"), DateTime("1851-03-16T09:00:00"), DateTime("1851-12-16T09:00:00"), DateTime("1852-01-16T09:00:00"), Date

In [9]:
(psl_historical_monthly, psl_ssp126_monthly, psl_ssp585_monthly) = build_ensemble_data(psl_data_monthly_path, "historical", "ssp126", "ssp585"; file_range_selection=:, data_field_id="psl", member_range=1:50, filterfun = winter_timelimit)

Handling scenario historical ...
Handling scenario ssp126 ...
Handling scenario ssp585 ...


3-element Vector{EnsembleSimulation}:
 EnsembleSimulation("historical", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), Date

In [ ]:
(ps_historical_monthly, ps_ssp126_monthly, ps_ssp585_monthly) = build_ensemble_data(ps_data_monthly_path, "historical", "ssp126", "ssp585"; file_range_selection=:, data_field_id="ps", member_range=1:50, filterfun = winter_timelimit)

In [78]:
(pr_historical_monthly, pr_ssp126_monthly, pr_ssp585_monthly) = build_ensemble_data(pr_data_monthly_path, "historical", "ssp126", "ssp585"; file_range_selection=:, data_field_id="pr", member_range=1:50, filterfun = winter_timelimit)

Handling scenario historical ...
Handling scenario ssp126 ...
Handling scenario ssp585 ...


3-element Vector{EnsembleSimulation}:
 EnsembleSimulation("historical", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), Date

In [ ]:
ssp126_full_timeline = concat_ensemble_data(ivt_historical_monthly, ivt_ssp126_monthly; id = "IVT historical + ssp126")

In [32]:
ivt_ssp585_full_timeline = concat_ensemble_data(ivt_historical_monthly, ivt_ssp585_monthly; id = "IVT historical + ssp585")

EnsembleSimulation("IVT historical + ssp585", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-14T21:00:00"), DateTime("1850-03-16T09:00:00"), DateTime("1850-12-16T09:00:00"), DateTime("1851-01-16T09:00:00"), DateTime("1851-02-14T21:00:00"), DateTime("1851-03-16T09:00:00"), DateTime("1851-12-16T09:00:00"), DateTime("1852-01-16T09:00:00"), DateTime("1852-02-15T09:00:00"

In [12]:
psl_ssp585_full_timeline = concat_ensemble_data(psl_historical_monthly, psl_ssp585_monthly; id = "Sea Level Pressure historical + ssp585")

EnsembleSimulation("Sea Level Pressure historical + ssp585", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), DateTime("1852-

In [11]:
ps_ssp585_full_timeline = concat_ensemble_data(ps_historical_monthly, ps_ssp585_monthly; id = "ps historical + ssp585")

EnsembleSimulation("ps historical + ssp585", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-14T21:00:00"), DateTime("1850-03-16T09:00:00"), DateTime("1850-12-16T09:00:00"), DateTime("1851-01-16T09:00:00"), DateTime("1851-02-14T21:00:00"), DateTime("1851-03-16T09:00:00"), DateTime("1851-12-16T09:00:00"), DateTime("1852-01-16T09:00:00"), DateTime("1852-02-15T09:00:00")

In [79]:
pr_ssp585_full_timeline = concat_ensemble_data(pr_historical_monthly, pr_ssp585_monthly; id = "pr historical + ssp585")

EnsembleSimulation("pr historical + ssp585", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), DateTime("1852-02-15T12:00:00")

In [28]:
(ps_piControl, ) = build_ensemble_data(ps_data_monthly_path, "piControl"; file_range_selection=1:13, data_field_id="ps", member_range=1:1, filterfun = winter_timelimit)
(ivt_piControl, ) = build_ensemble_data(ivt_data_monthly_path, "piControl"; file_range_selection=1:13, data_field_id="ivt", member_range=1:1, filterfun = winter_timelimit)
(pr_piControl, ) = build_ensemble_data(pr_data_monthly_path, "piControl"; file_range_selection=1:13, data_field_id="pr", member_range=1:1, filterfun = winter_timelimit)


Handling scenario piControl ...
Handling scenario piControl ...
Handling scenario piControl ...


1-element Vector{EnsembleSimulation}:
 EnsembleSimulation("piControl", Union{Missing, AbstractFloat}[-90.0, -88.125, -86.25, -84.375, -82.5, -80.625, -78.75, -76.875, -75.0, -73.125  …  22.5, 24.375, 26.25, 28.125, 30.0, 31.875, 33.75, 35.625, 37.5, 39.375], Union{Missing, AbstractFloat}[21.450475037398185, 23.31573072614093, 25.180985581270594, 27.04623949994481, 28.91149236871774, 30.77674406172325, 32.64199443851768, 34.50724334150103, 36.37249059281224, 38.23773599056483  …  62.48557052203639, 64.35073040887207, 66.2158721139987, 68.08099098565125, 69.94608064698343, 71.81113211427447, 73.67613231320912, 75.54106145287895, 77.4058880820788, 79.27055903485967], Union{Missing, DateTime}[DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), DateT

In [63]:
ivt_piControl.time[end] < DateTime(2100, 12, 31)

false

In [72]:
# load eof data

ivt_eof_ssp585_50seasons = load_eof_ensemble(eof_data_path, "50seasons", "ssp585", "ivt"; scale_eofs=nothing, align_with_first=2:5)


EOFEnsemble("ivt", [DateTime("1850-01-16T12:00:00"), DateTime("1850-02-14T21:00:00"), DateTime("1850-03-16T09:00:00"), DateTime("1850-12-16T09:00:00"), DateTime("1851-01-16T09:00:00"), DateTime("1851-02-14T21:00:00"), DateTime("1851-03-16T09:00:00"), DateTime("1851-12-16T09:00:00"), DateTime("1852-01-16T09:00:00"), DateTime("1852-02-15T09:00:00")  …  DateTime("2098-03-16T09:00:00"), DateTime("2098-12-16T09:00:00"), DateTime("2099-01-16T09:00:00"), DateTime("2099-02-14T21:00:00"), DateTime("2099-03-16T09:00:00"), DateTime("2099-12-16T09:00:00"), DateTime("2100-01-16T09:00:00"), DateTime("2100-02-14T21:00:00"), DateTime("2100-03-16T09:00:00"), DateTime("2100-12-16T09:00:00")], UnitRange{Int64}[1:199, 4:203, 8:207, 12:211, 16:215, 20:219, 24:223, 28:227, 32:231, 36:235  …  768:967, 772:971, 776:975, 780:979, 784:983, 788:987, 792:991, 796:995, 800:999, 804:1003], EOFResult[EOFResult([-0.004306771791776437 0.004433708289433605 … 0.0022665484426568016 0.0020355669784067366; -0.0055408759204

In [70]:
pr_eof_ssp585_50seasons = load_eof_ensemble(eof_data_path, "50seasons", "ssp585", "pr"; scale_eofs=nothing, align_with_first=2:5)

EOFEnsemble("pr", [DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), DateTime("1852-02-15T12:00:00")  …  DateTime("2098-03-16T12:00:00"), DateTime("2098-12-16T12:00:00"), DateTime("2099-01-16T12:00:00"), DateTime("2099-02-15T00:00:00"), DateTime("2099-03-16T12:00:00"), DateTime("2099-12-16T12:00:00"), DateTime("2100-01-16T12:00:00"), DateTime("2100-02-15T00:00:00"), DateTime("2100-03-16T12:00:00"), DateTime("2100-12-16T12:00:00")], UnitRange{Int64}[1:199, 4:203, 8:207, 12:211, 16:215, 20:219, 24:223, 28:227, 32:231, 36:235  …  768:967, 772:971, 776:975, 780:979, 784:983, 788:987, 792:991, 796:995, 800:999, 804:1003], EOFResult[EOFResult([-0.007313624721639045 0.0046129515721250874 … 0.0008941995746265906 0.00010085418257437193; -0.006051965652

In [25]:
ps_eof_ssp585_50seasons = load_eof_ensemble(eof_data_path, "50seasons", "ssp585", "ps"; scale_eofs=svalmult)

EOFEnsemble("ps", [DateTime("1850-01-16T12:00:00"), DateTime("1850-02-14T21:00:00"), DateTime("1850-03-16T09:00:00"), DateTime("1850-12-16T09:00:00"), DateTime("1851-01-16T09:00:00"), DateTime("1851-02-14T21:00:00"), DateTime("1851-03-16T09:00:00"), DateTime("1851-12-16T09:00:00"), DateTime("1852-01-16T09:00:00"), DateTime("1852-02-15T09:00:00")  …  DateTime("2098-12-16T09:00:00"), DateTime("2099-01-16T09:00:00"), DateTime("2099-02-14T21:00:00"), DateTime("2099-03-16T09:00:00"), DateTime("2099-12-16T09:00:00"), DateTime("2100-01-16T09:00:00"), DateTime("2100-02-14T21:00:00"), DateTime("2100-03-16T09:00:00"), DateTime("2100-12-16T09:00:00"), DateTime("2101-01-01T00:00:00")], UnitRange{Int64}[1:201, 4:205, 8:209, 12:213, 16:217, 20:221, 24:225, 28:229, 32:233, 36:237  …  777:978, 781:982, 785:986, 789:990, 793:995, 797:999, 801:1003, 805:1007, 809:1011, 813:1015], EOFResult[EOFResult([79.78724336607267 86.30548997079588 … -478.4604635042845 -494.59217823736157; 68.65749217040836 77.79332

In [71]:
psl_eof_ssp585_50seasons = load_eof_ensemble(eof_data_path, "50seasons", "ssp585", "psl"; scale_eofs=nothing, align_with_first=2:5)

EOFEnsemble("psl", [DateTime("1850-01-16T12:00:00"), DateTime("1850-02-15T00:00:00"), DateTime("1850-03-16T12:00:00"), DateTime("1850-12-16T12:00:00"), DateTime("1851-01-16T12:00:00"), DateTime("1851-02-15T00:00:00"), DateTime("1851-03-16T12:00:00"), DateTime("1851-12-16T12:00:00"), DateTime("1852-01-16T12:00:00"), DateTime("1852-02-15T12:00:00")  …  DateTime("2098-03-16T12:00:00"), DateTime("2098-12-16T12:00:00"), DateTime("2099-01-16T12:00:00"), DateTime("2099-02-15T00:00:00"), DateTime("2099-03-16T12:00:00"), DateTime("2099-12-16T12:00:00"), DateTime("2100-01-16T12:00:00"), DateTime("2100-02-15T00:00:00"), DateTime("2100-03-16T12:00:00"), DateTime("2100-12-16T12:00:00")], UnitRange{Int64}[1:199, 4:203, 8:207, 12:211, 16:215, 20:219, 24:223, 28:227, 32:231, 36:235  …  768:967, 772:971, 776:975, 780:979, 784:983, 788:987, 792:991, 796:995, 800:999, 804:1003], EOFResult[EOFResult([0.006450886416040827 0.006946328860401858 … -0.03842976952699851 -0.040255234857076994; 0.0055566806781372

In [24]:
compare_ensembles(
    2,
    "eof_videos/eof_v3_comparison_ivt_pr_ensemble_2modes_ssp585_monthlymean_50seasons_correctscale_hexbinsv2.mp4",
    (ivt_ssp585_full_timeline, ivt_eof_ssp585_50seasons, "IVT in kg s-1 m-1", 1.0),
    (pr_ssp585_full_timeline, pr_eof_ssp585_50seasons, "Preciptation in mm/month", 86400.0);
    framerate=5,
    colormap=:vik100,
    coastline_color=:black,
    shading=NoShading,
    resolution=(2000, 1000),
    fontsize=12,
    whole_figure_title="Comparison of EOF results of SSP585 IVT and Precipitation",
    contours_for_slice=1:2,
    contour_mode = :hexbin,
    hexbin_colormap = :algae,
    testmode = false
)

In [ ]:
compare_ensembles(
    2,
    "eof_videos/eof_v3_comparison_ivt_ensemble_2modes_ssp126_ssp585_monthlymean_50seasons_correctscale_hexbinsv2.mp4",
    (ivt_ssp585_full_timeline, ivt_eof_ssp585_50seasons, "IVT in kg s-1 m-1", 1.0),
    (ps_ssp585_full_timeline, ps_eof_ssp585_50seasons, "PS in hPa", 1/100);
    framerate=5,
    colormap=:vik100,
    coastline_color=:black,
    shading=NoShading,
    resolution=(2000, 1000),
    fontsize=12,
    whole_figure_title="Comparison of EOF results of Scenario ssp126 and ssp585",
    contours_for_slice=1:2,
    contour_mode = :hexbin,
    hexbin_colormap = :algae,
    testmode = false
)

In [76]:
boxplot_fig = generate_correlation_boxplot(
    ivt_eof_ssp585_50seasons,
    psl_eof_ssp585_50seasons;
    compare_modes = 2 => 2, 
    data_name = "Mode 2 of Monthly IVT and Mode 2 of Sea Level Pressure (EAP) SSP585", 
    size = (1500, 1000),
    value_mode=:absolute,
    transformation=nothing,
    legend_position = :rb
)

Available members in both datasets: 50


In [77]:
save("correlation_figures/correlation_boxplot_ivt_psl_mode22_historical_ssp585_piControl_eofv3.png", boxplot_fig)

In [46]:
temporal_pattern_integration(
    ivt_eof_ssp585_50seasons; 
    mode = 1, 
    data_name="", 
    size=(1500, 1000), 
    value_mode=:absolute, 
    transformation=nothing, 
    legend_position = :rt
)

In [87]:
function get_correlation_map(variable_data, temporal_pattern)

    x, y = size(variable_data)

    println("$x, $y")

    result = ones(x, y)

    for i in 1:x
        for j in 1:y
            result[i, j] = cor(variable_data[i, j, :], temporal_pattern)
        end
    end
    
    return result
    
end

get_correlation_map (generic function with 1 method)

In [89]:
ensemble_simulation = pr_ssp585_full_timeline

fig = Figure()

lonmin, lonmax = extrema(ensemble_simulation.lons)
latmin, latmax = extrema(ensemble_simulation.lats)

mode_ax = local_geoaxis_creation!(fig, (lonmin, lonmax), (latmin, latmax); title="Mode 1", figure_row= 1, figure_col=1)

scope = ivt_eof_ssp585_50seasons.scopes[1]

eof_res = ivt_eof_ssp585_50seasons.ensemble[get_member_id_string(11)][1]

pr_data = ensemble_simulation.members[11].data[:, :, scope]

cor_map = get_correlation_map(pr_data, eof_res.temporal_modes[:, 1])

surf = surface!(mode_ax, (lonmin, lonmax), (latmin, latmax), cor_map, color=:vik100)

lines!(mode_ax, GeoMakie.coastlines(); color=:black, transformation=(; translation=(0, 0, 1000)))

Colorbar(fig[1, 2], suf, ticks = -1:0.25:1)

fig

70, 32
