In [1]:
using LinearAlgebra

In [2]:
data = rand(100, 600)

100×600 Matrix{Float64}:
 0.932296  0.825656   0.125887   …  0.22468    0.0537087   0.577645
 0.544362  0.456774   0.280234      0.71453    0.274275    0.394358
 0.945633  0.138681   0.0297578     0.103411   0.0189657   0.186461
 0.830634  0.841867   0.0543144     0.922984   0.460204    0.753144
 0.983132  0.215893   0.597401      0.446122   0.635324    0.35034
 0.274087  0.252354   0.0753426  …  0.0217098  0.596917    0.347905
 0.74211   0.304963   0.97392       0.953216   0.0508156   0.114879
 0.555048  0.0203113  0.822058      0.287886   0.272279    0.628444
 0.474296  0.508759   0.959615      0.855758   0.679616    0.586142
 0.508996  0.930254   0.669245      0.0403012  0.00298749  0.84938
 ⋮                               ⋱                         
 0.508218  0.660798   0.458618      0.704215   0.773848    0.77415
 0.13466   0.384182   0.652186      0.358342   0.292997    0.868785
 0.855924  0.468729   0.604453      0.767169   0.170069    0.870333
 0.44243   0.334042   0.121507    

In [3]:
left_singular_vectors, singular_vals, right_singular_vectors = svd(data)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
100×100 Matrix{Float64}:
 -0.10073    -0.100243     0.0221071  …   0.120278   -0.00199223   0.0331927
 -0.103312    0.169664    -0.120677       0.255209    0.0325184    0.0229086
 -0.101433   -0.112509    -0.0834625     -0.0698619  -0.0114549   -0.155451
 -0.100563    0.0203698   -0.068815       0.0617031   0.0845692   -0.103463
 -0.101354    0.00934636  -0.0698674     -0.0135936   0.23415     -0.0793091
 -0.0995598   0.0137324   -0.14363    …   0.12145    -0.0244736    0.0729791
 -0.0976853   0.0194764   -0.0966488      0.02511     0.0268783   -0.132796
 -0.0994882  -0.0660031   -0.0231477      0.160008    0.218682     0.067262
 -0.105002   -0.239897     0.104496      -0.0271791   0.213065     0.121459
 -0.0984895  -0.0748074    0.0967678     -0.0396042   0.0340933   -0.0760773
  ⋮                                   ⋱                           
 -0.100201   -0.169494    -0.11244        0.0320461   0.0751281   -0.0140242


In [4]:
flips = [-1 ; ones(99)]

100-element Vector{Float64}:
 -1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  ⋮
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0

In [5]:
singular_vals

100-element Vector{Float64}:
 122.47221532123915
   9.8826909750416
   9.645586503095704
   9.558199760142337
   9.295292668297328
   9.236988652108328
   9.114394685311618
   9.067485625965125
   9.048964997906019
   8.973724325688698
   ⋮
   4.89649245065014
   4.816801008311829
   4.786108956521575
   4.7338986544838315
   4.6652345367894235
   4.619711755163962
   4.494820537281317
   4.4717567107661464
   4.331868871984781

In [6]:
function reconstruct(left_singular_vectors, singular_vals, right_singular_vectors)
    return left_singular_vectors * Diagonal(singular_vals) * right_singular_vectors'
end

reconstruct (generic function with 1 method)

In [7]:
reconstructed = reconstruct(left_singular_vectors, singular_vals, right_singular_vectors)

100×600 Matrix{Float64}:
 0.932296  0.825656   0.125887   …  0.22468    0.0537087   0.577645
 0.544362  0.456774   0.280234      0.71453    0.274275    0.394358
 0.945633  0.138681   0.0297578     0.103411   0.0189657   0.186461
 0.830634  0.841867   0.0543144     0.922984   0.460204    0.753144
 0.983132  0.215893   0.597401      0.446122   0.635324    0.35034
 0.274087  0.252354   0.0753426  …  0.0217098  0.596917    0.347905
 0.74211   0.304963   0.97392       0.953216   0.0508156   0.114879
 0.555048  0.0203113  0.822058      0.287886   0.272279    0.628444
 0.474296  0.508759   0.959615      0.855758   0.679616    0.586142
 0.508996  0.930254   0.669245      0.0403012  0.00298749  0.84938
 ⋮                               ⋱                         
 0.508218  0.660798   0.458618      0.704215   0.773848    0.77415
 0.13466   0.384182   0.652186      0.358342   0.292997    0.868785
 0.855924  0.468729   0.604453      0.767169   0.170069    0.870333
 0.44243   0.334042   0.121507    

In [8]:
diffs = data .- reconstructed

extrema(diffs)

(-1.1657341758564144e-14, 9.880984919163893e-15)

In [9]:
right_singular_vectors

600×100 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.0468527  -0.00120957  -0.0341439    …  -0.0339185    0.0148575
 -0.0412842  -0.00825795  -0.000307893     -0.0450478   -0.00618564
 -0.0400676  -0.0474237   -0.0303329        0.0569086   -0.0333348
 -0.041104   -0.0101911   -0.0151573        0.0350801    0.0149209
 -0.0419961  -0.0279883   -0.0451783       -0.00145623   0.0155644
 -0.0433492  -0.0181931    0.0124946    …  -0.0125229   -0.0865621
 -0.0397595   0.0683355   -0.0454891        0.0325269   -0.0124536
 -0.0437631   0.00705055   0.0347683       -0.0133395   -0.0725447
 -0.0441073  -0.0931785    0.0300894        0.0201321    0.0633726
 -0.0409849   0.016583    -0.014959        -0.0291933   -0.0901783
  ⋮                                     ⋱               
 -0.0378936   0.0223689   -0.0269976        0.0197636    0.0591354
 -0.0418609  -0.017793     0.0385773        0.0297638   -0.0469935
 -0.0358115   0.0132946   -0.0202245        0.0518228   -0.00186854
 -0.041085    

In [11]:
# now flip one axis

flipped_rights = right_singular_vectors .* reshape(flips, 1, :)

600×100 Matrix{Float64}:
 0.0468527  -0.00120957  -0.0341439    …  -0.0339185    0.0148575
 0.0412842  -0.00825795  -0.000307893     -0.0450478   -0.00618564
 0.0400676  -0.0474237   -0.0303329        0.0569086   -0.0333348
 0.041104   -0.0101911   -0.0151573        0.0350801    0.0149209
 0.0419961  -0.0279883   -0.0451783       -0.00145623   0.0155644
 0.0433492  -0.0181931    0.0124946    …  -0.0125229   -0.0865621
 0.0397595   0.0683355   -0.0454891        0.0325269   -0.0124536
 0.0437631   0.00705055   0.0347683       -0.0133395   -0.0725447
 0.0441073  -0.0931785    0.0300894        0.0201321    0.0633726
 0.0409849   0.016583    -0.014959        -0.0291933   -0.0901783
 ⋮                                     ⋱               
 0.0378936   0.0223689   -0.0269976        0.0197636    0.0591354
 0.0418609  -0.017793     0.0385773        0.0297638   -0.0469935
 0.0358115   0.0132946   -0.0202245        0.0518228   -0.00186854
 0.041085    0.0185367    0.0258343        0.00664986   0.0

In [12]:
reconstructed_one_flipped = reconstruct(left_singular_vectors, singular_vals, flipped_rights)

100×600 Matrix{Float64}:
 -0.223711  -0.192956   -0.862709   …  -0.813338  -0.912151   -0.435197
 -0.641279  -0.587949   -0.733704      -0.350098  -0.716345   -0.644448
 -0.21845   -0.887047   -0.965744      -0.941859  -0.953642   -0.833457
 -0.32346   -0.175059   -0.932645      -0.113317  -0.504057   -0.258022
 -0.180043  -0.809035   -0.397325      -0.598334  -0.336525   -0.668782
 -0.868493  -0.754427   -0.901771   …  -1.00425   -0.357724   -0.653173
 -0.378957  -0.682862    0.0152036     -0.053429  -0.885852   -0.86735
 -0.58671   -0.985746   -0.154353      -0.737338  -0.681676   -0.371914
 -0.730746  -0.55306    -0.0709149     -0.226291  -0.327213   -0.469662
 -0.6213    -0.065703   -0.297364      -0.974631  -0.941391   -0.140936
  ⋮                                 ⋱                         
 -0.641718  -0.352465   -0.524787      -0.328352  -0.18694    -0.233373
 -1.04692   -0.656966   -0.358282      -0.702642  -0.694232   -0.166465
 -0.299077  -0.548997   -0.383283      -0.269947 

In [13]:
reconstructed_both_flipped = reconstruct(left_singular_vectors .* reshape(flips, 1, :), singular_vals, flipped_rights)

100×600 Matrix{Float64}:
 0.932296  0.825656   0.125887   …  0.22468    0.0537087   0.577645
 0.544362  0.456774   0.280234      0.71453    0.274275    0.394358
 0.945633  0.138681   0.0297578     0.103411   0.0189657   0.186461
 0.830634  0.841867   0.0543144     0.922984   0.460204    0.753144
 0.983132  0.215893   0.597401      0.446122   0.635324    0.35034
 0.274087  0.252354   0.0753426  …  0.0217098  0.596917    0.347905
 0.74211   0.304963   0.97392       0.953216   0.0508156   0.114879
 0.555048  0.0203113  0.822058      0.287886   0.272279    0.628444
 0.474296  0.508759   0.959615      0.855758   0.679616    0.586142
 0.508996  0.930254   0.669245      0.0403012  0.00298749  0.84938
 ⋮                               ⋱                         
 0.508218  0.660798   0.458618      0.704215   0.773848    0.77415
 0.13466   0.384182   0.652186      0.358342   0.292997    0.868785
 0.855924  0.468729   0.604453      0.767169   0.170069    0.870333
 0.44243   0.334042   0.121507    

In [14]:
maximum(data .- reconstructed_both_flipped)

9.880984919163893e-15

In [15]:
maximum(data .- reconstructed_one_flipped)

1.2200193732022688