In [4]:
using LinearAlgebra

In [2]:
data = rand(100, 600)

100×600 Matrix{Float64}:
 0.199433   0.547568  0.670362   …  0.181509    0.864643   0.306134
 0.679988   0.75612   0.774297      0.239116    0.908397   0.788278
 0.95497    0.595456  0.932347      0.465879    0.685239   0.399492
 0.0515716  0.420391  0.115707      0.260293    0.331278   0.439166
 0.910947   0.09335   0.97546       0.825391    0.134524   0.769162
 0.869947   0.83159   0.0501543  …  0.17575     0.59407    0.652048
 0.320421   0.72499   0.409362      0.835327    0.701628   0.782222
 0.721602   0.99621   0.539531      0.108113    0.369445   0.0756977
 0.68132    0.621476  0.429415      0.805096    0.060765   0.780113
 0.301805   0.388913  0.43061       0.657405    0.298866   0.777257
 ⋮                               ⋱                         
 0.186161   0.410429  0.142555      0.627522    0.414311   0.0359214
 0.296494   0.223549  0.987621      0.0311397   0.724372   0.0613875
 0.108038   0.513754  0.595319      0.499401    0.391974   0.546087
 0.0449635  0.955334  0.5903

In [5]:
left_singular_vectors, singular_vals, right_singular_vectors = svd(data)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
100×100 Matrix{Float64}:
 -0.102123    0.227287    -0.0157894   …   0.00258755  -0.0904142
 -0.100388    0.0193921   -0.0919479       0.059367    -0.0181948
 -0.0995595  -0.297188    -0.0272445       0.167933    -0.00309774
 -0.0970021   0.0560337    0.023666       -0.0948886   -0.138776
 -0.0979541  -0.0619577    0.027787       -0.095506    -0.031993
 -0.0992532  -0.0256323    0.0336484   …  -0.0891146   -0.0276059
 -0.101532   -0.139661    -0.0141777      -0.0989837    0.0239876
 -0.0991424  -0.0153443    0.0105801      -0.0428737    0.11372
 -0.101466   -0.00518964   0.06765        -0.0724998    0.090754
 -0.0991086   0.173414    -0.00196041      0.179022     0.0711781
  ⋮                                    ⋱               
 -0.100508    0.0144604    0.114693       -0.0864912   -0.0290685
 -0.101753    0.0710602    0.00707568      0.0215532   -0.0225641
 -0.0993711   0.00654988  -0.147845       -0.143341     0.0549368

In [8]:
flips = [-1 ; ones(99)]

100-element Vector{Float64}:
 -1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  ⋮
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0

In [14]:
singular_vals

100-element Vector{Float64}:
 122.82638479050009
   9.797140911683025
   9.57820131467126
   9.534934626336103
   9.383175968083451
   9.354303057008975
   9.288171820377926
   9.172963100279304
   9.142528550088727
   9.077313828988471
   ⋮
   4.967691768727343
   4.903813404835465
   4.804133716275368
   4.747401634576605
   4.597749143377168
   4.552479004947949
   4.495553163432325
   4.427400793528323
   4.3764101407456995

In [35]:
function reconstruct(left_singular_vectors, singular_vals, right_singular_vectors)
    return left_singular_vectors * Diagonal(singular_vals) * right_singular_vectors'
end

reconstruct (generic function with 1 method)

In [36]:
reconstructed = reconstruct(left_singular_vectors, singular_vals, right_singular_vectors)

100×600 Matrix{Float64}:
 0.199433   0.547568  0.670362   …  0.181509    0.864643   0.306134
 0.679988   0.75612   0.774297      0.239116    0.908397   0.788278
 0.95497    0.595456  0.932347      0.465879    0.685239   0.399492
 0.0515716  0.420391  0.115707      0.260293    0.331278   0.439166
 0.910947   0.09335   0.97546       0.825391    0.134524   0.769162
 0.869947   0.83159   0.0501543  …  0.17575     0.59407    0.652048
 0.320421   0.72499   0.409362      0.835327    0.701628   0.782222
 0.721602   0.99621   0.539531      0.108113    0.369445   0.0756977
 0.68132    0.621476  0.429415      0.805096    0.060765   0.780113
 0.301805   0.388913  0.43061       0.657405    0.298866   0.777257
 ⋮                               ⋱                         
 0.186161   0.410429  0.142555      0.627522    0.414311   0.0359214
 0.296494   0.223549  0.987621      0.0311397   0.724372   0.0613875
 0.108038   0.513754  0.595319      0.499401    0.391974   0.546087
 0.0449635  0.955334  0.5903

In [45]:
diffs = data .- reconstructed

extrema(diffs)

(-9.520162436160717e-15, 1.176836406102666e-14)

In [39]:
right_singular_vectors

600×100 adjoint(::Matrix{Float64}) with eltype Float64:
 -0.0406155  -0.0725888    -0.0115053   …  -0.0653939    0.042429
 -0.046459   -0.0186289     0.0333788      -0.00874773   0.0328903
 -0.0395789  -0.00500023   -0.00952673      0.0393869    0.059732
 -0.0431712  -0.0288613    -0.0402566      -0.00940386   0.0551976
 -0.0427029  -0.0162389    -0.0293075       0.0848717    0.0430972
 -0.0410411  -0.0533635     0.00508051  …  -0.0170726   -0.0244479
 -0.0407498   0.0183725     0.00414491     -0.0457956    0.0543806
 -0.0423788   0.0151069    -0.0322175       0.0486693    0.0259725
 -0.0389383   0.0214264     0.0230482       0.0554938    0.0482005
 -0.0370887   0.0241875     0.018277        0.0297864    0.064194
  ⋮                                     ⋱               
 -0.0412685   0.00487219    0.0350956      -0.00479432   0.0436144
 -0.0440711  -0.0502906    -0.0127366      -0.0652578    0.0655974
 -0.038087   -0.00556303    0.0300958      -0.0365923   -0.00952629
 -0.0417529   0.00

In [40]:
# now flip one axis

flipped_rights = right_singular_vectors .* reshape(flips, 1, :)

600×100 Matrix{Float64}:
 0.0406155  -0.0725888    -0.0115053   …  -0.0653939    0.042429
 0.046459   -0.0186289     0.0333788      -0.00874773   0.0328903
 0.0395789  -0.00500023   -0.00952673      0.0393869    0.059732
 0.0431712  -0.0288613    -0.0402566      -0.00940386   0.0551976
 0.0427029  -0.0162389    -0.0293075       0.0848717    0.0430972
 0.0410411  -0.0533635     0.00508051  …  -0.0170726   -0.0244479
 0.0407498   0.0183725     0.00414491     -0.0457956    0.0543806
 0.0423788   0.0151069    -0.0322175       0.0486693    0.0259725
 0.0389383   0.0214264     0.0230482       0.0554938    0.0482005
 0.0370887   0.0241875     0.018277        0.0297864    0.064194
 ⋮                                     ⋱               
 0.0412685   0.00487219    0.0350956      -0.00479432   0.0436144
 0.0440711  -0.0502906    -0.0127366      -0.0652578    0.0655974
 0.038087   -0.00556303    0.0300958      -0.0365923   -0.00952629
 0.0417529   0.00420795    0.0138707      -0.00534477  -0.01566

In [41]:
reconstructed_one_flipped = reconstruct(left_singular_vectors, singular_vals, flipped_rights)

100×600 Matrix{Float64}:
 -0.819477   -0.617935  -0.322542    …  -0.818311   -0.108299   -0.757965
 -0.321613   -0.389584  -0.20174        -0.74372    -0.0480167  -0.257745
 -0.0383671  -0.540795  -0.0356363      -0.508847   -0.263283   -0.6379
 -0.916249   -0.686673  -0.827411       -0.689395   -0.59288    -0.571579
 -0.0663729  -1.02458    0.0230859      -0.133618   -0.798703   -0.251502
 -0.120334   -0.301164  -0.914851    …  -0.795977   -0.351535   -0.382152
 -0.692597   -0.433773  -0.577801       -0.158712   -0.265688   -0.275725
 -0.267574   -0.135281  -0.424397       -0.862531   -0.575105   -0.957349
 -0.331041   -0.536535  -0.557106       -0.188298   -0.905923   -0.277146
 -0.687033   -0.742191  -0.532989       -0.312906   -0.645361   -0.255437
  ⋮                                  ⋱                          
 -0.816642   -0.736649  -0.834652       -0.356493   -0.54325    -1.01136
 -0.718725   -0.937731  -0.00168523     -0.965058   -0.245045   -0.998857
 -0.883419   -0.620346  -

In [43]:
reconstructed_both_flipped = reconstruct(left_singular_vectors .* reshape(flips, 1, :), singular_vals, flipped_rights)

100×600 Matrix{Float64}:
 0.199433   0.547568  0.670362   …  0.181509    0.864643   0.306134
 0.679988   0.75612   0.774297      0.239116    0.908397   0.788278
 0.95497    0.595456  0.932347      0.465879    0.685239   0.399492
 0.0515716  0.420391  0.115707      0.260293    0.331278   0.439166
 0.910947   0.09335   0.97546       0.825391    0.134524   0.769162
 0.869947   0.83159   0.0501543  …  0.17575     0.59407    0.652048
 0.320421   0.72499   0.409362      0.835327    0.701628   0.782222
 0.721602   0.99621   0.539531      0.108113    0.369445   0.0756977
 0.68132    0.621476  0.429415      0.805096    0.060765   0.780113
 0.301805   0.388913  0.43061       0.657405    0.298866   0.777257
 ⋮                               ⋱                         
 0.186161   0.410429  0.142555      0.627522    0.414311   0.0359214
 0.296494   0.223549  0.987621      0.0311397   0.724372   0.0613875
 0.108038   0.513754  0.595319      0.499401    0.391974   0.546087
 0.0449635  0.955334  0.5903

In [44]:
maximum(data .- reconstructed_both_flipped)

1.176836406102666e-14

In [42]:
maximum(data .- reconstructed_one_flipped)

1.2414863237285485